-- Create application role if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'nutriplan_app') THEN
    CREATE ROLE nutriplan_app WITH LOGIN PASSWORD 'nutriplan_app_secret' NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END $$;

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO nutriplan_app;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO nutriplan_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nutriplan_app;

-- Make future tables accessible too
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO nutriplan_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO nutriplan_app;

-- Force RLS on all domain tables (even for table owners)
ALTER TABLE "Tenant" FORCE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Patient" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PatientProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PatientCondition" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Consultation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Protocol" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FoodCanonical" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FoodAlias" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FoodNutrient" FORCE ROW LEVEL SECURITY;
ALTER TABLE "DatasetRelease" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ImportJob" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ValidationReport" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PatientDataPolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PatientCategoryOverride" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FoodSnapshot" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Meal" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MealItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Plan" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PlanVersion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PlanItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PlanApproval" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PlanPublication" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CalcAudit" FORCE ROW LEVEL SECURITY;
ALTER TABLE "IntegrityCheckRun" FORCE ROW LEVEL SECURITY;
ALTER TABLE "IntegrityIssue" FORCE ROW LEVEL SECURITY;

-- Grant execute on functions
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO nutriplan_app;
